// Generates src/components/iconMap.ts with explicit named imports so that
// only the icons actually referenced in content are bundled (tree-shaking friendly).
import { readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'

const roots = ['src/data', 'src/data/topics']
const names = new Set()
const extra = [
  'ShieldCheck','Bug','Network','Radar','ScrollText','Search','ArrowRight','ArrowLeft','Menu','X',
  'Sun','Moon','BookOpen','GraduationCap','FlaskConical','Bookmark','BookmarkCheck','Check','ChevronRight',
  'ChevronDown','Play','Pause','Sparkles','Github','Linkedin','Mail','ExternalLink','Download','Home',
  'Layers','Target','Trophy','CircleCheck','CircleX','TriangleAlert','Lightbulb','Wrench','Link2','Quote',
  'ListChecks','Filter','RotateCcw','Command','CornerDownLeft','Star','Clock','Gauge','Cpu','Lock','Eye',
]
extra.forEach((n) => names.add(n))

for (const dir of roots) {
  for (const f of readdirSync(dir, { withFileTypes: true })) {
    if (!f.isFile() || !f.name.endsWith('.ts')) continue
    const src = readFileSync(join(dir, f.name), 'utf8')
    for (const m of src.matchAll(/icon:\s*'([A-Za-z0-9]+)'/g)) names.add(m[1])
  }
}

const sorted = [...names].sort()
const out = `// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// Explicit imports keep the lucide bundle limited to icons actually used.
import {
${sorted.map((n) => '  ' + n + ',').join('\n')}
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

export const ICONS: Record<string, LucideIcon> = {
${sorted.map((n) => '  ' + n + ',').join('\n')}
}

export const getIcon = (name?: string): LucideIcon => (name && ICONS[name]) || ICONS.Sparkles
`
writeFileSync('src/components/iconMap.ts', out)
console.log('icons:', sorted.length)
